version: '3.1'

services:
  gpgen:
    container_name: FakeGreenPassGenerator
    build: ./FakeGreenPassGenerator
    volumes:
      - "./FakeGreenPassGenerator:/app"
  # qrcodegen:
  #   container_name: QRCodeGen
  #   build: ./QRCodeGenerator
  #   volumes:
  #     - "./QRCodeGenerator:/app"

